basePath: /api/admin
definitions:
  internal_handlers.MessageResponse:
    properties:
      message:
        type: string
    type: object
  internal_handlers.createServiceRequest:
    properties:
      host:
        minLength: 1
        type: string
      name:
        minLength: 1
        type: string
      retry_count:
        minimum: 0
        type: integer
      retry_interval:
        minimum: 0
        type: number
      scheme:
        enum:
        - https
        - http
        type: string
      targets:
        items:
          $ref: '#/definitions/internal_handlers.target'
        type: array
      timeout:
        type: number
    required:
    - host
    - name
    - retry_count
    - retry_interval
    - scheme
    - targets
    - timeout
    type: object
  internal_handlers.target:
    properties:
      cache_interval:
        type: string
      method:
        enum:
        - GET
        - POST
        - PUT
        - DELETE
        type: string
      path:
        type: string
      query:
        type: string
    required:
    - method
    - path
    - query
    type: object
  internal_handlers.updateServiceRequest:
    properties:
      host:
        minLength: 1
        type: string
      retry_count:
        minimum: 0
        type: integer
      retry_interval:
        minimum: 0
        type: number
      scheme:
        enum:
        - https
        - http
        type: string
      targets:
        items:
          $ref: '#/definitions/internal_handlers.target'
        type: array
      timeout:
        type: number
      version:
        minimum: 0
        type: integer
    required:
    - host
    - retry_count
    - retry_interval
    - scheme
    - targets
    - timeout
    - version
    type: object
  proxy-service_internal_models.ServiceDTO:
    properties:
      host:
        type: string
      name:
        type: string
      retry_count:
        type: integer
      retry_interval:
        type: number
      scheme:
        type: string
      targets:
        items:
          $ref: '#/definitions/proxy-service_internal_models.TargetDTO'
        type: array
      timeout:
        type: number
      version:
        type: integer
    type: object
  proxy-service_internal_models.TargetDTO:
    properties:
      cache_interval:
        type: string
      method:
        type: string
      path:
        type: string
      query:
        type: string
    type: object
info:
  contact: {}
  description: API for managing info about allowed services and targets to proxy
  title: Proxy Service Admin API
  version: "1.0"
paths:
  /ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
      summary: Ping
      tags:
      - Common API
  /v1/service:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            items:
              $ref: '#/definitions/proxy-service_internal_models.ServiceDTO'
            type: array
      summary: Get all services with targets
      tags:
      - Admin API
    post:
      consumes:
      - application/json
      parameters:
      - description: Service data (with targets)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.createServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
        "409":
          description: Service already exists
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
      summary: Create service
      tags:
      - Admin API
  /v1/service/{name}:
    delete:
      parameters:
      - description: Service name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
      summary: Delete service
      tags:
      - Admin API
    get:
      parameters:
      - description: Service name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/proxy-service_internal_models.ServiceDTO'
        "404":
          description: Service not found
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
      summary: Get service with targets by name
      tags:
      - Admin API
    put:
      consumes:
      - application/json
      parameters:
      - description: Service name
        in: path
        name: name
        required: true
        type: string
      - description: Service data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.updateServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
        "404":
          description: Service not found
          schema:
            $ref: '#/definitions/internal_handlers.MessageResponse'
      summary: Update service
      tags:
      - Admin API
swagger: "2.0"
