apiVersion: v1
kind: Secret
metadata:
  name: proxy-service-db-secret
type: Opaque
stringData:
  PG_USER: "<replace-with-db-user>"
  PG_PASSWORD: "<replace-with-db-password>"
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-service-redis-secret
type: Opaque
stringData:
  REDIS_PASSWORD: ""
