proxy_server:
  port: 8080
  pg:
    user: proxy_service_user
    password: proxy_service_password
    host: postgres
    port: 5432
    database: proxy_service_db
    sslmode: disable
  redis:
    master_name: redis-proxy
    hosts:
      - redis-sentinel-1:26379
      - redis-sentinel-2:26379
      - redis-sentinel-3:26379
    password: proxy_service_password
    database: 0
    pool_size: 20
mock_server:
  port: 8081
  response_status_code: 200
admin_server:
  port: 8082
  pg:
    user: proxy_service_user
    password: proxy_service_password
    host: postgres
    port: 5432
    database: proxy_service_db
    sslmode: disable
background_worker:
  concurrency: 4
  redis:
    master_name: redis-proxy
    hosts:
      - redis-sentinel-1:26379
      - redis-sentinel-2:26379
      - redis-sentinel-3:26379
    password: proxy_service_password
    database: 0
    pool_size: 20
background_scheduler:
  redis:
    master_name: redis-proxy
    hosts:
      - redis-sentinel-1:26379
      - redis-sentinel-2:26379
      - redis-sentinel-3:26379
    password: proxy_service_password
    database: 0
    pool_size: 20
  pg:
    user: proxy_service_user
    password: proxy_service_password
    host: postgres
    port: 5432
    database: proxy_service_db
    sslmode: disable
