- name: mock
  host: localhost:8081
  scheme: http
  targets:
    - path: /mock
      method: GET
    - path: /mock
      method: POST
    - path: /mock
      method: PUT
    - path: /mock
      method: DELETE
  timeout: 10.0
  retry_count: 3
  retry_interval: 0.1
